
NUM_WORKERS = 5 
INITIAL_NODES = ["node-1", "node-2", "node-3", "node-4", "node-5"] 
TASK_GENERATION_INTERVAL = 0.2  

AGENT_HEARTBEAT_INTERVAL = 10  
MONITOR_CHECK_INTERVAL = 15   
SCHEDULER_PULL_INTERVAL = 0.1   
RESOURCE_MANAGER_CHECK_INTERVAL = 5 

TASK_EXECUTION_TIME_MIN = 2   
TASK_EXECUTION_TIME_MAX = 6  


HIGH_CPU_THRESHOLD = 70.0 
LOW_CPU_THRESHOLD = 40.0  
SCALE_OUT_QUEUE_THRESHOLD = 10 
SCALE_IN_LOAD_THRESHOLD = 0.6 
WORKER_COOLDOWN_PERIOD = 10 

LOAD_BALANCER_ID = "load_balancer"
RESOURCE_MANAGER_ID = "resource_manager"
MONITOR_AGENT_ID = "monitor_agent"
SCHEDULER_ID = "scheduler"
DASHBOARD_ID = "dashboard"
CLUSTER_MANAGER_ID = "cluster_manager"

MESSAGE_BUS_PULL_TIMEOUT = 1.0 